services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./bus_booking/:/usr/src/bus_booking/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=$(SQL_USER)
      - POSTGRES_PASSWORD=$(SQL_PASSWORD)
      - POSTGRES_DB=$(SQL_DATABASE)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bus_booking/static:/static
      - ./bus_booking/media:/media
    depends_on:
      - web

volumes:
  postgres_data:
