# Generated by Django 5.1.6 on 2025-02-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(related_name='bookings_passengers', to='booking_system.passenger'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_bookings', to='booking_system.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_bus', to='booking_system.bus'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='next_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_system.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='route_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_segments', to='booking_system.routesegment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedules',
            field=models.ManyToManyField(related_name='bookings_schedule', to='booking_system.schedule'),
        ),
        migrations.AddField(
            model_name='routesegment',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_segment', to='booking_system.stop'),
        ),
        migrations.AddField(
            model_name='routesegment',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_of_segment', to='booking_system.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_stop', to='booking_system.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_stop', to='booking_system.stop'),
        ),
    ]
