# Generated by Django 5.1.6 on 2025-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='pending', max_length=20),
        ),
    ]
